-- P0 多租户隔离:为业务表补 tenant_id(根公司 org_id)并回填现有数据到租户 1。
ALTER TABLE cap_projects ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_projects_tenant (tenant_id);
UPDATE cap_projects SET tenant_id=1;
ALTER TABLE cap_funds ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_funds_tenant (tenant_id);
UPDATE cap_funds SET tenant_id=1;
ALTER TABLE cap_risk_incidents ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_risk_incidents_tenant (tenant_id);
UPDATE cap_risk_incidents SET tenant_id=1;
ALTER TABLE cap_documents ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_documents_tenant (tenant_id);
UPDATE cap_documents SET tenant_id=1;
ALTER TABLE cap_workflow_instances ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_workflow_instances_tenant (tenant_id);
UPDATE cap_workflow_instances SET tenant_id=1;
ALTER TABLE cap_workflow_tasks ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_workflow_tasks_tenant (tenant_id);
UPDATE cap_workflow_tasks SET tenant_id=1;
ALTER TABLE cap_investors ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_investors_tenant (tenant_id);
UPDATE cap_investors SET tenant_id=1;
ALTER TABLE cap_announcements ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_announcements_tenant (tenant_id);
UPDATE cap_announcements SET tenant_id=1;
ALTER TABLE cap_calendar_events ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_calendar_events_tenant (tenant_id);
UPDATE cap_calendar_events SET tenant_id=1;
ALTER TABLE cap_messages ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_messages_tenant (tenant_id);
UPDATE cap_messages SET tenant_id=1;
ALTER TABLE cap_investment_positions ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_investment_positions_tenant (tenant_id);
UPDATE cap_investment_positions SET tenant_id=1;
ALTER TABLE cap_equity_changes ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_equity_changes_tenant (tenant_id);
UPDATE cap_equity_changes SET tenant_id=1;
ALTER TABLE cap_research_notes ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_research_notes_tenant (tenant_id);
UPDATE cap_research_notes SET tenant_id=1;
ALTER TABLE cap_import_export_tasks ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_import_export_tasks_tenant (tenant_id);
UPDATE cap_import_export_tasks SET tenant_id=1;
ALTER TABLE cap_recycle_items ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_recycle_items_tenant (tenant_id);
UPDATE cap_recycle_items SET tenant_id=1;
ALTER TABLE cap_audit_logs ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_audit_logs_tenant (tenant_id);
UPDATE cap_audit_logs SET tenant_id=1;
ALTER TABLE cap_ui_action_events ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_ui_action_events_tenant (tenant_id);
UPDATE cap_ui_action_events SET tenant_id=1;
ALTER TABLE cap_data_collection_campaigns ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_data_collection_campaigns_tenant (tenant_id);
UPDATE cap_data_collection_campaigns SET tenant_id=1;
ALTER TABLE cap_project_stage_events ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_project_stage_events_tenant (tenant_id);
UPDATE cap_project_stage_events SET tenant_id=1;
ALTER TABLE cap_risk_updates ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_risk_updates_tenant (tenant_id);
UPDATE cap_risk_updates SET tenant_id=1;
ALTER TABLE cap_management_orgs ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_management_orgs_tenant (tenant_id);
UPDATE cap_management_orgs SET tenant_id=1;
ALTER TABLE cap_document_versions ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_document_versions_tenant (tenant_id);
UPDATE cap_document_versions SET tenant_id=1;
ALTER TABLE cap_document_permissions ADD COLUMN tenant_id BIGINT UNSIGNED NULL, ADD INDEX idx_cap_document_permissions_tenant (tenant_id);
UPDATE cap_document_permissions SET tenant_id=1;
